### ISSUE TITLE
引入gist时会存在少许问题

### ISSUE THREAD

**Issue by Svtter** [Ben02/hexo-theme-Anatole#1]
很棒的主题！我在使用时发现了一点小问题：

![image](https://cloud.githubusercontent.com/assets/5856931/22181938/ce58ad30-e0d2-11e6-8cf8-a041b7e6dd8f.png)

使用`<script>`方式引入gist代码会产生一定错误。

**Comment by Ben02** [comment]
有线上的演示吗🙏我去看看。。因为我这边要复现的话会比较麻烦

**Comment by Svtter** [comment]
请看这里：
http://svtter.info/2017/01/22/Golang%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/#map

**Comment by Ben02** [comment]
md..不会用git，提交了几个冗余的commit...总之先这样了= = 
修复好了，bug是因为类highlight样式覆盖到gist引用上面了。

**Comment by Svtter** [comment]
@Ben02 问题已经修复。感谢！
