### ISSUE TITLE
没有生成正确的页面

### ISSUE THREAD

**Issue by zhuscat** [Ben02/hexo-theme-Anatole#14]
```
extends partial/layout block content .autopagerize_page_element: .content - page.posts.each(function (item) { include mixins +make_post(item, false) - }) include mixins +make_pager(__('prev'), __('next'))
```

主题改成了 anotole 并且添加了 wiki 里说的几个配置，然后主页显示这个，不知道是怎么回事

**Comment by Ben02** [comment]
是mac平台吗？目前已经有两个mac用户反馈了，初步检查到是hexo-renderer-jade的问题，因为依赖这个插件的主题如hexo-theme-apollo也会出现相似的问题。因为是插件的锅所以暂时无解。

**Comment by zhuscat** [comment]
@Ben02 是的，可惜了，很漂亮的主题~

**Comment by ranshon** [comment]
先执行这个： 
npm install --save hexo-renderer-jade hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive 

再执行 git clone 就 OK 了
引自：https://www.v2ex.com/amp/t/362017
