### ISSUE TITLE
找不到文件ds-embed.css

### ISSUE THREAD

**Issue by Qiozi** [Ben02/hexo-theme-Anatole#2]
你好，我把hexo 默认的主题改为anatole后， 发现有个css文件报404错误，我看了themes下的css文件夹，也没有这个文件：ds-embed.css
hexo 原来的默认的主题是不会要加载这个文件的。

**Comment by Ben02** [comment]
这是多说评论框的CSS文件，你看下 _config.yml 的 duoshuo: 字段有没有设置对，如果不想用多说请把这个字段删掉。加载不了 ds-embed.css 估计只是多说服务器不稳定的问题。这个主题并没有要加载这个 CSS。

**Comment by Ben02** [comment]
建议隔一段时间多刷新几遍看下能不能加载，能加载的话就是多说服务器的锅了。还是不行的话，如果有部署到线上的页面请给我看一下。

**Comment by Ben02** [comment]
看了一下，是我在调试主题的时候有的代码没有删干净… 现在更新了应该没有问题了🙊

**Comment by Qiozi** [comment]
我更新了，现在正常。
