### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by SourceCipher** [Ben02/hexo-theme-Anatole#22]
Once I transfer this theme, the website simply wont work -> http://prntscr.com/gvrlgy

**Comment by SourceCipher** [comment]
Nvm, I found a fix which was not included in the readme file
run this in order to support jade and other juices
`npm install --save hexo-renderer-jade hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive`

**Comment by Ben02** [comment]
thank you
