### ISSUE TITLE
使用主题时，生成的路径会多一个s字母

### ISSUE THREAD

**Issue by izuolan** [Ben02/hexo-theme-Anatole#6]
![image](https://cloud.githubusercontent.com/assets/5241553/23100299/b7015a82-f6b8-11e6-913c-24f688e8282e.png)

导致所有js、css都不能加载。换其他主题都没有这个问题。

**Comment by Ben02** [comment]
？这不是主题的锅吧？检查一下固定链接

**Comment by izuolan** [comment]
好快，我都没打完，躺倒。
