### ISSUE TITLE
对于网易云跟贴的支持

### ISSUE THREAD

**Issue by iPixelOldC** [Ben02/hexo-theme-Anatole#7]
表示多说快废了。。。所以能不能支持下网易的东西（https://gentie.163.com/index.html），我自己尝试了好多次。。。全部失败噗（hoc117.top)（源码生成成功。。。但是无法显示）（表示我不懂Jade不懂HTML和JS之类的。。。这个Jade靠HTML转Jade）
所以您能不能做个支持呢？谢谢

**Comment by SuperRay3** [comment]
请问 about 页和 link 页怎么生成？  并且 rss 怎么设置？

**Comment by Ben02** [comment]
在网易云跟帖那里弄个通用代码发给我吧，我好看着改

**Comment by SmallFatCYW** [comment]
```
<div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
<script>
  var cloudTieConfig = {
    url: document.location.href, 
    sourceId: "",
    productKey: "这里是KEY",
    target: "cloud-tie-wrapper"
  };
</script>
<script src="https://img1.cache.netease.com/f2e/tie/yun/sdk/loader.js"></script>
```

**Comment by Ben02** [comment]
现在切换到 preview 分支，就能试用这个新功能了。在 _config.yml 里填好 `gentie: `，生成看下吧，等待你的反馈。

**Comment by SmallFatCYW** [comment]
抱歉啊，马上要考试了，我最近没时间测试。。。我等考完试后，再来测试一下:D

**Comment by SmallFatCYW** [comment]
抱歉啊，马上要考试了，我最近没时间测试。。。我等考完试后，再来测试一下:D
